# Required Rewrite Rule
location / {
    try_files $uri $uri/ /index.php?$args;
}

# We should always hide Sensitive Information
server_tokens off;

# Request Recommended by Mozilla
location ~* \.(gif|ico|jpe?g|png|svg|svgz|webp)$ {
    add_header Access-Control-Allow-Origin *;
}

# Allow Webfont access from other locations. (handy)
location ~* \.(eot|font.css|css|otf|ttc|ttf|woff|woff2)$ {
    add_header Access-Control-Allow-Origin *;
}

# Prevent 404 Errors for Non-Existing Redirected Folders
error_page 403 /error/403;
error_page 404 /error/404;

# we also want UTF-8 Encoding
charset utf-8;

# Disallow users to view folders with no content
autoindex off;

location ~* \.(bak|config|dist|fla|inc|ini|log|psd|sh|sql|swp|~)$ {
    deny all;
    access_log off;
    log_not_found off;
}

# Headers Module start
location ~* \.(js|css|xml|gz|html|ttf)$ {
    add_header Vary Accept-Encoding;
}

# Gzip Compression start
gzip on;
gzip_types text/plain text/css text/xml application/javascript application/x-javascript text/javascript image/svg+xml application/font-woff application/x-font-ttf font/opentype font/otf font/ttf;

# Keep Alive start
keepalive_timeout 65;

# Optimize default expiration time
location ~* \.(bmp|gif|jpg|jpeg|jp2|jpe|png|svg|svgz|tiff|ico|icon|txt|css|js|pdf|zip|rar|doc|xls|exe|ppt|tar|mid|midi|mp3|ogg|ogv|mp4|m4v|webm|flv|aac|swf|woff|woff2|eot|ttf|otf)$ {
    expires 1w;
    add_header Cache-Control "public";
}

# deny direct access on git
location ~ /\.git {
    deny all;
    access_log off;
    log_not_found off;
}
